"use client";

import { emailClassificationLabels } from "@/config/labels";
import { StatusBadge } from "@/components/status-badge";
import { formatDate, formatNumber } from "@/lib/format";
import type { EvaluatedCreator } from "@/types/domain";

export function CreatorTable({ creators, onSelect }: { creators: EvaluatedCreator[]; onSelect: (creator: EvaluatedCreator) => void }): React.ReactNode {
  return <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-4 py-3">채널</th><th className="px-4 py-3">카테고리</th><th className="px-4 py-3 text-right">구독자</th><th className="px-4 py-3 text-right">최근 평균 조회</th><th className="px-4 py-3">최근 업로드</th><th className="px-4 py-3">이메일 검증</th><th className="px-4 py-3">판정</th><th className="px-4 py-3">판정 사유</th></tr></thead><tbody className="divide-y divide-slate-100">{creators.map((creator) => <tr key={creator.identity.internalId} className="hover:bg-slate-50"><td className="px-4 py-4"><button type="button" onClick={() => onSelect(creator)} className="text-left font-semibold text-ink hover:text-brand hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand">{creator.identity.channelName}</button>{creator.identity.canonicalChannelUrl ? <a href={creator.identity.canonicalChannelUrl} target="_blank" rel="noreferrer" className="mt-1 block max-w-48 truncate text-xs text-slate-400 hover:text-brand">확인된 채널 URL ↗</a> : <span className="mt-1 block text-xs text-amber-600">채널 URL 미확인</span>}<span className="mt-1 block text-[10px] font-semibold text-blue-600">목 데이터</span></td><td className="px-4 py-4 text-slate-600">{creator.identity.category}</td><td className="px-4 py-4 text-right tabular-nums">{creator.evidence.subscriberCount === null ? "미확인" : formatNumber(creator.evidence.subscriberCount)}</td><td className="px-4 py-4 text-right font-medium tabular-nums">{creator.evidence.recentAverageViews === null ? "미확인" : formatNumber(creator.evidence.recentAverageViews)}</td><td className="px-4 py-4 text-slate-600">{creator.evidence.latestUploadDate ? formatDate(creator.evidence.latestUploadDate) : "미확인"}</td><td className="px-4 py-4 text-slate-600">{emailClassificationLabels[creator.evidence.emailClassification]}</td><td className="px-4 py-4"><StatusBadge status={creator.decision} /></td><td className="max-w-sm px-4 py-4 text-xs leading-5 text-slate-500"><p>{creator.koreanExplanation}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{creator.reasonCodes.join(", ") || "조건 통과"}</p></td></tr>)}</tbody></table></div>;
}
