"use client";

import { useEffect, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { creatorCategories } from "@/config/labels";
import { defaultRecommendationSettings, recommendationSettingsSchema } from "@/config/recommendation-rules";
import type { RecommendationSettings } from "@/types/domain";

const storageKey = "creator-recommendation-settings-v2";

export default function SettingsPage(): React.ReactNode {
  const [settings, setSettings] = useState<RecommendationSettings>(defaultRecommendationSettings); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const stored = window.localStorage.getItem(storageKey); if (!stored) return; try { const parsed: unknown = JSON.parse(stored); setSettings(recommendationSettingsSchema.parse(parsed)); } catch (caught) { console.error("저장된 설정을 불러오지 못했습니다.", caught); setError("저장된 설정이 유효하지 않아 기본값을 사용합니다."); } }, []);
  const setNumber = (key: "minimumRecentAverageViews" | "maximumDaysSinceLatestUpload" | "minimumRecentVideoCount" | "preferredRecentVideoCount", value: number): void => { setSettings((current) => ({ ...current, [key]: value })); setSaved(false); setError(""); };
  const toggleCategory = (category: string): void => { setSettings((current) => ({ ...current, allowedCategories: current.allowedCategories.includes(category) ? current.allowedCategories.filter((item) => item !== category) : [...current.allowedCategories, category] })); setSaved(false); };
  const save = (): void => { try { const validated = recommendationSettingsSchema.parse(settings); window.localStorage.setItem(storageKey, JSON.stringify(validated)); setSaved(true); setError(""); } catch (caught) { console.error("설정 저장에 실패했습니다.", caught); setError("활동 기간은 42~56일이며 허용 카테고리를 하나 이상 선택해야 합니다."); } };
  return <><PageHeader title="추천 기준 설정" description="결정론적 평가 엔진의 기준을 이 브라우저에 저장합니다." /><div className="panel max-w-3xl p-5 sm:p-8">{error && <p className="mb-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700" role="alert">{error}</p>}<div className="grid gap-6 sm:grid-cols-2"><SettingNumber label="최소 최근 평균 조회수" value={settings.minimumRecentAverageViews} onChange={(value) => setNumber("minimumRecentAverageViews", value)} min={0} /><SettingNumber label="최근 업로드 허용 최대 경과일" value={settings.maximumDaysSinceLatestUpload} onChange={(value) => setNumber("maximumDaysSinceLatestUpload", value)} min={42} max={56} /><SettingNumber label="최소 최근 영상 수" value={settings.minimumRecentVideoCount} onChange={(value) => setNumber("minimumRecentVideoCount", value)} min={2} /><SettingNumber label="선호 최근 영상 수" value={settings.preferredRecentVideoCount} onChange={(value) => setNumber("preferredRecentVideoCount", value)} min={3} /></div><div className="mt-6 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-600">구독자 수 기준은 현재 설정하지 않았으며 판정에 사용하지 않습니다. 최근 평균은 기본 5개, 근거가 충분하면 최대 10개의 비교 가능한 동일 형식 영상을 사용합니다.</div><fieldset className="mt-8 border-t border-slate-200 pt-6"><legend className="font-semibold text-ink">허용 크리에이터 카테고리</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{creatorCategories.map((category) => <label key={category} className="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-3 hover:bg-slate-50"><input type="checkbox" checked={settings.allowedCategories.includes(category)} onChange={() => toggleCategory(category)} className="h-4 w-4 rounded border-slate-300 text-brand focus:ring-brand" /><span className="text-sm font-medium">{category}</span></label>)}</div></fieldset><div className="mt-8 flex items-center justify-end gap-4 border-t border-slate-200 pt-6">{saved && <span className="text-sm font-medium text-emerald-700" role="status">이 브라우저에 저장했습니다.</span>}<button type="button" onClick={save} className="button-primary">설정 저장</button></div></div></>;
}

function SettingNumber({ label, value, onChange, min, max }: { label: string; value: number; onChange: (value: number) => void; min: number; max?: number }): React.ReactNode { return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input type="number" min={min} max={max} className="input" value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
